apiVersion: v1
kind: Service
metadata:
  name: {{ include "KubeKit.fullname" . }}-svc
  labels:
    {{- include "KubeKit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ include "KubeKit.fullname" . }}
  selector:
    {{- include "KubeKit.selectorLabels" . | nindent 4 }}
